
all: start
 
start:
	zathura *.pdf & 2>error
drive:
	firefoxe https://docs.google.com/document/d/1GzoJ-4iHJGYdfP03uEElUNLmK6EW5qCX-W28ZUE6p-o/edit# &
task:
	task project:base_de_données

un deux trois:
	echo "un deux trois"
