
all: start
 
start:
	clear

savelaptop:
	cp -r ~/projet/calcurse/calcurse/todo ~/projet/calcurse/calcurse/apts ~/projet/calcurse/calcurse/notes ~/projet/calcurse/data

savemobile:
	cp -r ~/storage/downloads/projet/calcurse/data/todo ~/storage/downloads/projet/calcurse/data/apts ~/storage/downloads/projet/calcurse/data/notes ~/storage/downloads/projet/calcurse/calcurse

