
all: start
 
start:
	clear

savelaptop:
	cd ~/projet/calcurse && cp -r calcurse/todo caclurse/apts calcurse/notes data

savemobile:
	cp -r ~/storage/downloads/projet/calcurse/data/todo ~/storage/downloads/projet/calcurse/data/apts ~/storage/downloads/projet/calcurse/data/notes ~/storage/downloads/projet/calcurse/calcurse

