#!/bin/bash

#git remote update
#git status -uno

lastTaskName=$(echo hello world)
while [ 1 ]; do
	sleep 1

	nextTask=$(task due:now | sed '1,3d' | sed "/^\s*[[:digit:]]\+\s\+[[:alnum:]]\+\s\+-[[:alnum:]]\+\s\+[^$]\+$/d" | sed '2,$d')
	taskName=$(echo $nextTask | sed 's/\(\w\+\)\ \(\w\+\)\ \(\w\+\)\ \(.*\)/\4/')
	taskTime=$(echo $nextTask | sed 's/\(\w\+\)\ \(\w\+\)\ \(\w\+\)\ \(.*\)/\3/')


	if [ "$taskName" != "$lastTaskName" ]; then
		lastTaskName="$taskName"
		#écrire le code de notification
		echo $taskName
		echo temps restant $taskTime
	fi
done
