import random

pays= [
"Afghanistan",
"Iles Aland",
"Albanie",
"Algérie",
"Samoa américaines",
"Andorre",
"Angola",
"Anguilla",
"Antarctique",
"Antigua-et-Barbuda",
"Argentine",
"Arménie",
"Aruba",
"Australie",
"L’Autriche",
"Azerbaïdjan",
"Bahamas",
"Bahreïn",
"Bangladesh",
"Barbade",
"Biélorussie",
"Belgique",
"Belize",
"Bénin",
"Bermudes",
"Bhoutan",
"Bolivie (État plurinational de)",
"Bonaire, Saint Eustache et Saba",
"Bosnie Herzégovine",
"Botswana",
"Île Bouvet",
"Brésil",
"Territoire britannique de l’océan Indien",
"Brunei Darussalam",
"Bulgarie",
"Burkina Faso",
"Burundi",
"Cap-Vert",
"Cambodge",
"Cameroun",
"Canada",
"Îles Caïmans",
"République centrafricaine",
"Tchad",
"Chili",
"Chine",
"L’île de noël",
"Îles Cocos (Keeling)",
"Colombie",
"Comores",
"Congo",
"les Îles Cook",
"Costa Rica",
"Côte d’Ivoire",
"Croatie",
"Cuba",
"Curacao",
"Chypre",
"Tchéquie",
"République Populaire Démocratique de Corée",
"République Démocratique du Congo",
"Danemark",
"Djibouti",
"Dominique",
"République dominicaine",
"Equateur",
"Egypte",
"Le sauveur",
"Guinée Équatoriale",
"Érythrée",
"Estonie",
"Ethiopie",
"Union européenne",
"Îles Falkland (Malvinas)",
"Îles Féroé (membre associé)",
"Fidji",
"Finlande",
"France",
"Guyane Française",
"Polynésie française",
"Terres australes et antarctiques françaises",
"Gabon",
"Gambie",
"Géorgie",
"Allemagne",
"Ghana",
"Gibraltar",
"Grèce",
"Groenland",
"Grenade",
"Guadeloupe",
"Guam",
"Guatemala",
"Guernesey",
"Guinée",
"Guinée-Bissau",
"Guyane",
"Haïti",
"Île Heard et îles McDonald",
"Saint-Siège"]

rnd= random.Random()

def generate(generator):
    res= ""
    if generator == "number":
        res= str(random.randint(0,100))
    elif generator == "pays":
        res= rnd.choice(pays) 
    return res

