
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'langCOMA CP CSB EQUAL IN INF MINUS NAME NUM OP OSB SUP VAR\n    lang : premises MINUS MINUS conclusion\n    \n    premises : statements\n    \n    premises : \n    \n    statements : statement more\n    \n    statements : \n    \n    more : COMA statement more\n    \n    more : \n    \n    statement : exp sym exp\n    \n    sym : EQUAL\n        | MINUS SUP\n        | IN\n    \n    conclusion : statement\n    \n    exp : NAME OP exp CP\n    \n    exp : exp moreexp\n    \n    exp : NUM\n        | VAR\n    \n    term : NUM\n         | VAR\n         | list\n    \n    exp : list\n    \n    list : OSB morelist CSB\n    \n    morelist : term COMA morelist\n    \n    morelist : term\n    \n    list : OSB CSB\n    \n    list : INF morelist SUP\n    \n    moreexp : COMA exp moreexp\n    \n    moreexp : COMA exp\n    '
    
_lr_action_items = {'MINUS':([0,2,3,4,5,7,8,9,12,13,16,23,30,31,33,35,37,40,41,42,],[-3,12,-2,-7,18,-15,-16,-20,29,-4,-14,-24,-7,-8,-27,-21,-25,-6,-14,-13,]),'NAME':([0,14,15,17,19,20,21,29,32,],[6,6,6,-9,-11,6,6,6,-10,]),'NUM':([0,10,11,14,15,17,19,20,21,29,32,36,],[7,25,25,7,7,-9,-11,7,7,7,-10,25,]),'VAR':([0,10,11,14,15,17,19,20,21,29,32,36,],[8,26,26,8,8,-9,-11,8,8,8,-10,26,]),'OSB':([0,10,11,14,15,17,19,20,21,29,32,36,],[10,10,10,10,10,-9,-11,10,10,10,-10,10,]),'INF':([0,10,11,14,15,17,19,20,21,29,32,36,],[11,11,11,11,11,-9,-11,11,11,11,-10,11,]),'$end':([1,7,8,9,16,23,31,33,35,37,38,39,41,42,],[0,-15,-16,-20,-14,-24,-8,-27,-21,-25,-1,-12,-14,-13,]),'COMA':([4,5,7,8,9,16,23,24,25,26,27,30,31,33,34,35,37,41,42,],[14,20,-15,-16,-20,-14,-24,36,-17,-18,-19,14,20,20,20,-21,-25,-14,-13,]),'EQUAL':([5,7,8,9,16,23,33,35,37,41,42,],[17,-15,-16,-20,-14,-24,-27,-21,-25,-14,-13,]),'IN':([5,7,8,9,16,23,33,35,37,41,42,],[19,-15,-16,-20,-14,-24,-27,-21,-25,-14,-13,]),'OP':([6,],[21,]),'CP':([7,8,9,16,23,33,34,35,37,41,42,],[-15,-16,-20,-14,-24,-27,42,-21,-25,-14,-13,]),'CSB':([10,22,23,24,25,26,27,35,37,43,],[23,35,-24,-23,-17,-18,-19,-21,-25,-22,]),'SUP':([18,23,24,25,26,27,28,35,37,43,],[32,-24,-23,-17,-18,-19,37,-21,-25,-22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'lang':([0,],[1,]),'premises':([0,],[2,]),'statements':([0,],[3,]),'statement':([0,14,29,],[4,30,39,]),'exp':([0,14,15,20,21,29,],[5,5,31,33,34,5,]),'list':([0,10,11,14,15,20,21,29,36,],[9,27,27,9,9,9,9,9,27,]),'more':([4,30,],[13,40,]),'sym':([5,],[15,]),'moreexp':([5,31,33,34,],[16,16,41,16,]),'morelist':([10,11,36,],[22,28,43,]),'term':([10,11,36,],[24,24,24,]),'conclusion':([29,],[38,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> lang","S'",1,None,None,None),
  ('lang -> premises MINUS MINUS conclusion','lang',4,'p_lang','compile.py',70),
  ('premises -> statements','premises',1,'p_premisses1','compile.py',76),
  ('premises -> <empty>','premises',0,'p_premisses2','compile.py',82),
  ('statements -> statement more','statements',2,'p_statements1','compile.py',88),
  ('statements -> <empty>','statements',0,'p_statements2','compile.py',94),
  ('more -> COMA statement more','more',3,'p_more1','compile.py',100),
  ('more -> <empty>','more',0,'p_more2','compile.py',106),
  ('statement -> exp sym exp','statement',3,'p_statement','compile.py',112),
  ('sym -> EQUAL','sym',1,'p_sym','compile.py',118),
  ('sym -> MINUS SUP','sym',2,'p_sym','compile.py',119),
  ('sym -> IN','sym',1,'p_sym','compile.py',120),
  ('conclusion -> statement','conclusion',1,'p_conclusion','compile.py',126),
  ('exp -> NAME OP exp CP','exp',4,'p_exp_operator','compile.py',132),
  ('exp -> exp moreexp','exp',2,'p_exp_more','compile.py',138),
  ('exp -> NUM','exp',1,'p_exp_int','compile.py',144),
  ('exp -> VAR','exp',1,'p_exp_int','compile.py',145),
  ('term -> NUM','term',1,'p_term','compile.py',151),
  ('term -> VAR','term',1,'p_term','compile.py',152),
  ('term -> list','term',1,'p_term','compile.py',153),
  ('exp -> list','exp',1,'p_exp_list','compile.py',158),
  ('list -> OSB morelist CSB','list',3,'p_exp_list1','compile.py',164),
  ('morelist -> term COMA morelist','morelist',3,'p_exp_list2','compile.py',170),
  ('morelist -> term','morelist',1,'p_exp_list3','compile.py',176),
  ('list -> OSB CSB','list',2,'p_exp_list4','compile.py',182),
  ('list -> INF morelist SUP','list',3,'p_exp_list5','compile.py',188),
  ('moreexp -> COMA exp moreexp','moreexp',3,'p_more_exp','compile.py',194),
  ('moreexp -> COMA exp','moreexp',2,'p_more_empty','compile.py',200),
]
