COURS=project:phantsper
all: start
 
start:
	echo hello world!
revisions: FORCE
	cd ~/cours//revisions
exercices: FORCE
	cd ~/cours//exercices
tps: FORCE
	cd ~/cours//tps
addtask: FORCE
	task add $(ARGS) $(COURS)$(SUB)
summary: FORCE
	task $(COURS) summary
task: FORCE
	task $(COURS)$(SUB)
wiki: FORCE
	firefox https://sites.google.com/d/1HtpG9mzEfda5VUpIYg7rUGQUDk0WKKS_/p/1pGtNwGsdu6gFxQUPzV1gXQpgiVMncpgo/edit &
FORCE:


