COURS=project:phantsper
all: start
 
start:
	echo hello world!
revisions: FORCE
	cd ~/cours//revisions
exercices: FORCE
	cd ~/cours//exercices
tps: FORCE
	cd ~/cours//tps
addtask: FORCE
	task add $(ARGS) $(COURS)$(SUB)
summary: FORCE
	task $(COURS) summary
task: FORCE
	task $(COURS)$(SUB)
FORCE:

