
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMA CP NAME NUM OP\n    calc : exp\n    \n    exp : NAME OP exp CP\n    \n    exp : exp more\n    \n    exp : NUM\n    \n    more : COMA exp more\n    \n    more : COMA exp\n    '
    
_lr_action_items = {'NAME':([0,6,7,],[3,3,3,]),'NUM':([0,6,7,],[4,4,4,]),'$end':([1,2,4,5,8,10,11,],[0,-1,-4,-3,-6,-3,-2,]),'COMA':([2,4,5,8,9,10,11,],[6,-4,-3,6,6,-3,-2,]),'OP':([3,],[7,]),'CP':([4,5,8,9,10,11,],[-4,-3,-6,11,-3,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'calc':([0,],[1,]),'exp':([0,6,7,],[2,8,9,]),'more':([2,8,9,],[5,10,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> calc","S'",1,None,None,None),
  ('calc -> exp','calc',1,'p_calc','expression.py',52),
  ('exp -> NAME OP exp CP','exp',4,'p_exp_operator','expression.py',58),
  ('exp -> exp more','exp',2,'p_exp_more','expression.py',65),
  ('exp -> NUM','exp',1,'p_exp_int','expression.py',71),
  ('more -> COMA exp more','more',3,'p_more_exp','expression.py',77),
  ('more -> COMA exp','more',2,'p_more_empty','expression.py',83),
]
