
all: start
 
start:
	vim start.md

commandes:
	echo "
	start	start the project
	presence	pour la recherche de la présence de Dieu
	"

presence:
	firefox https://esperertoujours.fr/chercher-leternel/ &

