
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMA CP CSB NAME NUM OP OSB\n    calc : exp\n    \n    exp : NAME OP exp CP\n    \n    exp : exp more\n    \n    exp : NUM\n    \n    exp : list\n    \n    list : OSB morelist CSB\n    \n    morelist : NUM COMA morelist\n    \n    morelist : NUM\n    \n    list : OSB CSB\n    \n    more : COMA exp more\n    \n    more : COMA exp\n    '
    
_lr_action_items = {'NAME':([0,8,9,],[3,3,3,]),'NUM':([0,6,8,9,16,],[4,12,4,4,12,]),'OSB':([0,8,9,],[6,6,6,]),'$end':([1,2,4,5,7,11,13,15,17,18,],[0,-1,-4,-5,-3,-9,-11,-6,-3,-2,]),'COMA':([2,4,5,7,11,12,13,14,15,17,18,],[8,-4,-5,-3,-9,16,8,8,-6,-3,-2,]),'OP':([3,],[9,]),'CP':([4,5,7,11,13,14,15,17,18,],[-4,-5,-3,-9,-11,18,-6,-3,-2,]),'CSB':([6,10,12,19,],[11,15,-8,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'calc':([0,],[1,]),'exp':([0,8,9,],[2,13,14,]),'list':([0,8,9,],[5,5,5,]),'more':([2,13,14,],[7,17,7,]),'morelist':([6,16,],[10,19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> calc","S'",1,None,None,None),
  ('calc -> exp','calc',1,'p_calc','compile.py',79),
  ('exp -> NAME OP exp CP','exp',4,'p_exp_operator','compile.py',85),
  ('exp -> exp more','exp',2,'p_exp_more','compile.py',92),
  ('exp -> NUM','exp',1,'p_exp_int','compile.py',98),
  ('exp -> list','exp',1,'p_exp_list','compile.py',104),
  ('list -> OSB morelist CSB','list',3,'p_exp_list1','compile.py',110),
  ('morelist -> NUM COMA morelist','morelist',3,'p_exp_list2','compile.py',116),
  ('morelist -> NUM','morelist',1,'p_exp_list3','compile.py',122),
  ('list -> OSB CSB','list',2,'p_exp_list4','compile.py',128),
  ('more -> COMA exp more','more',3,'p_more_exp','compile.py',134),
  ('more -> COMA exp','more',2,'p_more_empty','compile.py',140),
]
