
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CB COMA DOT NAME OB\n    calc : exp\n    \n    exp : NAME OB exp CB next\n    \n    exp : exp more\n    \n    exp : NAME\n    \n    more : COMA exp more\n    \n    more : COMA exp\n    \n    next : DOT\n    \n    next : DOT exp\n    '
    
_lr_action_items = {'NAME':([0,5,6,12,],[3,3,3,3,]),'$end':([1,2,3,4,7,9,11,12,13,],[0,-1,-4,-3,-6,-3,-2,-7,-8,]),'COMA':([2,3,4,7,8,9,11,12,13,],[5,-4,-3,5,5,-3,-2,-7,5,]),'OB':([3,],[6,]),'CB':([3,4,7,8,9,11,12,13,],[-4,-3,-6,10,-3,-2,-7,-8,]),'DOT':([10,],[12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'calc':([0,],[1,]),'exp':([0,5,6,12,],[2,7,8,13,]),'more':([2,7,8,13,],[4,9,4,4,]),'next':([10,],[11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> calc","S'",1,None,None,None),
  ('calc -> exp','calc',1,'p_calc','compile.py',58),
  ('exp -> NAME OB exp CB next','exp',5,'p_exp_operator','compile.py',64),
  ('exp -> exp more','exp',2,'p_exp_more','compile.py',71),
  ('exp -> NAME','exp',1,'p_exp_int','compile.py',77),
  ('more -> COMA exp more','more',3,'p_more_exp','compile.py',83),
  ('more -> COMA exp','more',2,'p_more_empty','compile.py',89),
  ('next -> DOT','next',1,'p_next_empty','compile.py',95),
  ('next -> DOT exp','next',2,'p_next_exp','compile.py',101),
]
