
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMA CP DOUBLESEMICOLON NAME OP\n    calc : exp next\n    \n    exp : NAME OP exp CP \n    \n    exp : exp more\n    \n    exp : NAME \n    \n    more : COMA exp more\n    \n    more : COMA exp\n    \n    next : DOUBLESEMICOLON\n    \n    next : DOUBLESEMICOLON calc\n    '
    
_lr_action_items = {'NAME':([0,6,7,8,],[3,3,3,3,]),'$end':([1,4,6,9,],[0,-1,-7,-8,]),'DOUBLESEMICOLON':([2,3,5,10,12,13,],[6,-4,-3,-6,-3,-2,]),'COMA':([2,3,5,10,11,12,13,],[7,-4,-3,7,7,-3,-2,]),'OP':([3,],[8,]),'CP':([3,5,10,11,12,13,],[-4,-3,-6,13,-3,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'calc':([0,6,],[1,9,]),'exp':([0,6,7,8,],[2,2,10,11,]),'next':([2,],[4,]),'more':([2,10,11,],[5,12,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> calc","S'",1,None,None,None),
  ('calc -> exp next','calc',2,'p_calc','compile.py',72),
  ('exp -> NAME OP exp CP','exp',4,'p_exp_operator','compile.py',78),
  ('exp -> exp more','exp',2,'p_exp_more','compile.py',84),
  ('exp -> NAME','exp',1,'p_exp_name','compile.py',90),
  ('more -> COMA exp more','more',3,'p_more_exp','compile.py',96),
  ('more -> COMA exp','more',2,'p_more_empty','compile.py',102),
  ('next -> DOUBLESEMICOLON','next',1,'p_next_empty','compile.py',108),
  ('next -> DOUBLESEMICOLON calc','next',2,'p_next_exp','compile.py',114),
]
