
all: start
 
start:
	zathura *.pdf & 2>error && vim -S Session.vim 2>error && rm error

doc:	
	firefox http://tecfalabs.unige.ch/csaw/dw/doku.php?id=c-saw:c-saw_external_development#dashboard_development
traduction:
	firefox https://www.deepl.com/fr/translator

