
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMA CP CSB EQUAL INF NAME NUM OP OSB SUP\n    calc : exp\n    \n    calc : condition\n    \n    condition : exp comparator exp\n    \n    comparator : EQUAL EQUAL\n               | SUP\n               | SUP EQUAL\n               | INF\n               | INF EQUAL\n    \n    exp : NAME OP exp CP\n    \n    exp : exp more\n    \n    exp : NUM\n    \n    exp : list\n    \n    list : OSB morelist CSB\n    \n    morelist : NUM COMA morelist\n    \n    morelist : NUM\n    \n    list : OSB CSB\n    \n    list : INF morelist SUP\n    \n    more : COMA exp more\n    \n    more : COMA exp\n    '
    
_lr_action_items = {'NAME':([0,10,11,13,14,15,22,23,24,],[4,4,4,-5,-7,4,-4,-6,-8,]),'NUM':([0,7,8,10,11,13,14,15,22,23,24,27,],[5,18,18,5,5,-5,-7,5,-4,-6,-8,18,]),'OSB':([0,10,11,13,14,15,22,23,24,],[7,7,7,-5,-7,7,-4,-6,-8,]),'INF':([0,2,5,6,9,10,11,13,14,15,17,21,22,23,24,26,28,29,30,],[8,14,-11,-12,-10,8,8,-5,-7,8,-16,-19,-4,-6,-8,-13,-17,-10,-9,]),'$end':([1,2,3,5,6,9,17,20,21,26,28,29,30,],[0,-1,-2,-11,-12,-10,-16,-3,-19,-13,-17,-10,-9,]),'COMA':([2,5,6,9,17,18,20,21,25,26,28,29,30,],[11,-11,-12,-10,-16,27,11,11,11,-13,-17,-10,-9,]),'EQUAL':([2,5,6,9,12,13,14,17,21,26,28,29,30,],[12,-11,-12,-10,22,23,24,-16,-19,-13,-17,-10,-9,]),'SUP':([2,5,6,9,17,18,19,21,26,28,29,30,31,],[13,-11,-12,-10,-16,-15,28,-19,-13,-17,-10,-9,-14,]),'OP':([4,],[15,]),'CP':([5,6,9,17,21,25,26,28,29,30,],[-11,-12,-10,-16,-19,30,-13,-17,-10,-9,]),'CSB':([7,16,18,31,],[17,26,-15,-14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'calc':([0,],[1,]),'exp':([0,10,11,15,],[2,20,21,25,]),'condition':([0,],[3,]),'list':([0,10,11,15,],[6,6,6,6,]),'more':([2,20,21,25,],[9,9,29,9,]),'comparator':([2,],[10,]),'morelist':([7,8,27,],[16,19,31,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> calc","S'",1,None,None,None),
  ('calc -> exp','calc',1,'p_calc','Acompile.py',92),
  ('calc -> condition','calc',1,'p_calc2','Acompile.py',98),
  ('condition -> exp comparator exp','condition',3,'p_condition','Acompile.py',105),
  ('comparator -> EQUAL EQUAL','comparator',2,'p_comparator','Acompile.py',111),
  ('comparator -> SUP','comparator',1,'p_comparator','Acompile.py',112),
  ('comparator -> SUP EQUAL','comparator',2,'p_comparator','Acompile.py',113),
  ('comparator -> INF','comparator',1,'p_comparator','Acompile.py',114),
  ('comparator -> INF EQUAL','comparator',2,'p_comparator','Acompile.py',115),
  ('exp -> NAME OP exp CP','exp',4,'p_exp_operator','Acompile.py',121),
  ('exp -> exp more','exp',2,'p_exp_more','Acompile.py',128),
  ('exp -> NUM','exp',1,'p_exp_int','Acompile.py',134),
  ('exp -> list','exp',1,'p_exp_list','Acompile.py',140),
  ('list -> OSB morelist CSB','list',3,'p_exp_list1','Acompile.py',146),
  ('morelist -> NUM COMA morelist','morelist',3,'p_exp_list2','Acompile.py',152),
  ('morelist -> NUM','morelist',1,'p_exp_list3','Acompile.py',158),
  ('list -> OSB CSB','list',2,'p_exp_list4','Acompile.py',164),
  ('list -> INF morelist SUP','list',3,'p_exp_list5','Acompile.py',170),
  ('more -> COMA exp more','more',3,'p_more_exp','Acompile.py',176),
  ('more -> COMA exp','more',2,'p_more_empty','Acompile.py',182),
]
